version: 0.5.{build}

pull_requests:
  do_not_increment_build_number: false

skip_tags: true
  
image: Visual Studio 2019

init:
- ps: $env:customnugetversion = if ($env:APPVEYOR_REPO_TAG -eq $True) {  ("$env:APPVEYOR_REPO_TAG_NAME").TrimStart("v") } else { if ($env:APPVEYOR_PULL_REQUEST_NUMBER -ne "" -and $env:APPVEYOR_PULL_REQUEST_NUMBER -ne $null) { "$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH-pr$env:APPVEYOR_PULL_REQUEST_NUMBER" } else {"$env:APPVEYOR_BUILD_VERSION-$env:APPVEYOR_REPO_BRANCH" }}
- ps: Update-AppveyorBuild -Version $env:customnugetversion

before_build:
- ps: dotnet restore
# - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build:
  project: EaseLib.sln
  verbosity: minimal

artifacts:
- path: Artifacts/NuGet/*nupkg
  name: nugets

skip_commits:
  files:
    - '**\*.md'

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: j/i7K4TBOarCsC9rrzZSfTt8ww/51HtYutI0w2mnAcELOuqpQvkLRIDCoaPYYm++
  on:
    branch: master
    appveyor_repo_tag: true
  skip_symbols: false
  symbol_server: https://api.nuget.org/v3/index.json
#- provider: GitHub
#  auth_token:
#    secure: 
#  artifacts: nugets
#  tag: v$(appveyor_build_version)
#  on:
#    branch: master
#    appveyor_repo_tag: true